### ISSUE TITLE
[FEAT REQ]: swing through grass mod pretty please

### ISSUE THREAD

**Issue by budgethecat** [masuteri/pyonpack#2]
### Pyonpack version

0.4.2

### Suggestion(s)

i live in the jungle with a lot of grass and vines and creepers and whatnot
[https://modrinth.com/mod/cut-through](https://modrinth.com/mod/cut-through)

**Comment by masuteri** [comment]
Will try to add it in the next version

**Comment by nyxiereal** [comment]
Added
